/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imoney_simplecarddetector_CardDetector */

#ifndef _Included_com_imoney_simplecarddetector_CardDetector
#define _Included_com_imoney_simplecarddetector_CardDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imoney_simplecarddetector_CardDetector
 * Method:    nativeCreateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_imoney_simplecarddetector_CardDetector_nativeCreateObject
  (JNIEnv *, jclass);

/*
 * Class:     com_imoney_simplecarddetector_CardDetector
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_imoney_simplecarddetector_CardDetector_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_imoney_simplecarddetector_CardDetector
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_imoney_simplecarddetector_CardDetector_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
